#!/bin/bash
########################################################################
#Script modifiant les permissions (exécution) d'un fichier/dossier
#Nom du script: Rendre exécutable v1.1
#Auteur: Astohan
#Site Web: http://ankala.co.cc
#Licence: GPL v3
#Version 1.1: 
########################################################################
version="v1.1"	# Corrections mineures (polissage)

IFS="
"
	# On doit être sûr qu'un fichier est sélectionné
	# Détection du fichier 
	mime=`file -bi "$1"`;

	# On affiche le menu principal sous forme de liste-radio
	option=`zenity --list --radiolist --width="560" --height="210" --title="Rendre exécutable $version" --text="Choisir une action à effectuer" --column="Cocher" --column="Action" --column="Description" \
	TRUE "Fichier/Dossier" "Rendre le fichier sélectionné exécutable" \
	FALSE "Récursif" "Rendre un dossier et son contenu exécutables" `;

	# Opération sur un fichier ou dossier seléctionné
	if [ "$option" = "Fichier/Dossier" ]; then
		chmod ugo+x $1
	
	# On affiche une notification de réussite
	notify-send "Modification des permissions (exécution)" "Vous pouvez dorénavant lancer le fichier $1 simplement par double-clic !"
fi

	# Opération sur un dossier distant et tout son contenu
	if [ "$option" = "Récursif" ]; then
		chmod +x -R $1
	
	# On affiche une notification de réussite
	notify-send "Modification des permissions (exécution)" "Vous pouvez dorénavant lancer le fichier $1 aet l'ensemble de son contenu simplement par double-clic !"
fi
clean_temp
