#!/bin/bash
########################################################################
#Script affichant le nombre de mots contenus dans un fichier texte
#Nom du script: Statistiques du fichier v1.1
#Auteur: Astohan
#Site Web: http://ankala.co.cc
#Licence: GPL v3
# À venir en v1.2: Essayer de régler le problème avec les espaces dans les noms
########################################################################
version="v1.1.1"	# Correction d'un bug mineur

IFS="
"

	# On doit être sûr qu'un fichier est sélectionné
	# Détection du fichier 
	mime=`file -bi "$1"`;
a=$(wc -w $1 | cut -f1 -d' ')
b=$(wc -l $1 | cut -f1 -d' ')
c=$(wc -c $1 | cut -f1 -d' ')


zenity --info --title "Statistiques du fichier $version" \
--text="<u>Fichier analysé:</u> \n<b>$1</b> \n\n<u>Nombre de mots:</u> \n<b>$a mots</b> \
\n\n<u>Nombre de lignes:</u> \n<b>$b lignes</b> \
\n\n<u>Nombre de caractères:</u> \n<b>$c caractères</b>"\
;
