#!/bin/bash
########################################################################
#Script permettant de compresser tous les fichiers d'un même format
#Nom du script: Archivage groupé v1.1
#Auteur: Astohan
#Site Web: http://ankala.co.cc
#Licence: GPL v3
#À venir en v1.2: ?
########################################################################
version="v1.1"	# Corrections bugs mineurs

IFS="
"

	format=`zenity --entry --title="Archivage groupé $version" --entry-text="txt" --text="Veuillez entrer le format des fichiers à archiver.\n\nAttention: Tous les fichiers (du répertoire courant) du même format indiqué seront archivés.\n\nexemple: odt, txt, png, doc, php, etc..."`;
	if [ "$?" == 1 ] ; then exit 0 
	else
	archivage=`find . -name \*.$format | zip archive_"$format" -@ | zenity --progress --pulsate --title "Archivage en cours..." --text "Tous les fichiers de type <b>$format</b> sont en cours d'archivage." --auto-close`;
	notify-send "Archivage groupé" "Les fichiers $format ont été compressés dans l'archive "archive_$format" avec succès !"
fi
