#!/bin/bash
########################################################################
#Script capturant l'écran (screencast)
#Nom du script: Capture vidéo v1.2
#Auteur: Astohan
#Site Web: http://ankala.fr
#Source: Documentation de FFMPEG/AVCONV
#Licence: GPL v3
#À venir en v1.3: ?
########################################################################
version="v1.2"	# Corrections de bugs mineurs

	# On demande la durée de l'enregistrement, en minutes
	duree=`zenity --entry --title="Capture vidéo $version" --entry-text "00:01:00" --text="Définir la durée de l'enregistrement vidéo. \n\nPar exemple, 00:05:10 correspond à une durée de 5 minutes et 10 secondes."`

	# Si l'utilisateur annule, on quitte le script
	if [ "$?" == 1 ] ; then exit 1
	else
	# Sinon, on demande le nom du fichier final
	nom=`zenity --entry --title="Capture vidéo $version" --entry-text "capture_vidéo" --text="Entrez le nom du fichier contenant l'enregistrement final. \n\nN'ajoutez aucune extension au nom du fichier (avi, mp4, etc...)."`
fi
	# Si l'utilisateur annule, on quitte le script
	if [ "$?" == 1 ] ; then exit 1
	else
	# Sinon, on récupère la résolution du plein-écran, on démarre l'enregistrement, puis on affiche une notification à la fin
dimensions=`xdpyinfo | grep 'dimensions:' | head -1 | \
  sed -e 's/^.* \([0-9]\+x[0-9]\+\) pixels.*$/\1/'`

avconv -f x11grab \
  -r 30 -s $dimensions -i :0.0 \
  -f alsa -ac 2 -i pulse \
  -vcodec libx264 -pre:v lossless_ultrafast \
  -acodec libmp3lame \
  -t $duree -y $nom.avi
fi
	notify-send -i /usr/share/icons/Humanity/apps/48/checkbox.svg "Capture vidéo" "La capture vidéo a été correctement enregistrée sous le nom $nom.avi !"

	# On demande à ouvrir l'image générée dans 'Totem'
	question=$(zenity --question --title="Compression de la capture vidéo" --text "Voulez-vous ouvrir réduire le poids de la capture vidéo <b>$nom.avi</b> en la convertissant au format <b>MP4</b> ?" --ok-label="Compresser la vidéo" \ --cancel-label="Ne pas compresser")
	if [ "$?" == 1 ] ; then exit 1
	else
	# Sinon, on ouvre l'image dans Totem
	encode_video=`avconv -i "$nom".avi -vcodec libx264 -pre:v main -g 30 "$nom".mp4 \
	| zenity --progress --width="500" --pulsate --auto-close --title "Conversion en cours..." \
	--text "Conversion de <b>"$nom"</b> vers le format <b>MP4</b>."`;
	notify-send -i /usr/share/icons/Humanity/apps/48/totem.svg "Compression de la capture vidéo - MP4" "La capture vidéo $nom.avi a été compressée en $nom.mp4 !";
fi
