#!/bin/bash
########################################################################
#Script permettant d'ajouter/supprimer une bande sonore à une vidéo
#Nom du script: Manipuler la piste audio v1.2
#Auteur: Astohan
#Site Web: http://ankala.fr
#Source: Documentation de avconv
#Licence: GPL v3
#À venir en v1.2: ?
########################################################################
version="v1.2"	# Ajout de plus de formats audio/video

	# On s'assure que 'avconv' est bien installé
	avconv_exists=`which avconv | grep -c "avconv"`

	# On affiche une erreur si 'avconv' n'est pas installé
	# On tente une installation automatique de 'avconv'
	if [ $avconv_exists -eq 0 ]; then
		avconv_error=`zenity --error --title="Erreur - Outil de conversion manquant !" --text="Vous devez installer le paquet libav-tools afin d'utiliser ce script.\n\nTentative d'installation automatique amorcée."`;
		install_avconv=`gksudo apt-get install libav-tools | zenity --progress --pulsate --title "Installation de avconv" --text "Installation en cours..." --auto-close`;
	fi

	# On s'assure que l'installation automatique de 'avconv' a réussi
	avconv_exists2=`which avconv | grep -c "avconv"`
	
	# Si ce n'est pas le cas, on affiche une erreur et on quitte
	if [ $avconv_exists2 -eq 0 ]; then
		zenity --error --title="Erreur détectée !" --text="ERREUR: La tentative d'installation automatique a échouée. Veuillez installer libav-tools manuellement, à partir de votre terminal: sudo apt-get install libav-tools";
		exit;
	fi

	# On s'assure qu'un fichier est sélectionné et du MIME "video"
	mime=`file -bi "$1"`;
	correct_video=`echo "$mime" | grep video | wc -l`;

	# Si le fichier n'est pas de MIME "video"...
	if [ ! $correct_video -eq 1 ]; then
		zenity --error --title="Manipuler la piste audio $version" --text="Veuillez sélectionner un fichier vidéo valide."
		exit 1
	fi

	# Si le format vidéo est correct, afficher les options suivantes
	if [ $correct_video -eq 1 ]; then

	# Menu principal
	option=`zenity --list --radiolist --width="300" --height="200" --title="Manipuler la piste audio $version" --text="Choisir une action pour <i><b>$1</b></i>"  --column="Cocher" --column="Option" \
	TRUE "Extraire la bande sonore" \
	FALSE "Ajouter une bande sonore" \
	FALSE "Supprimer la bande sonore"`;

	if [ "$option" = "Ajouter une bande sonore" ]; then
	# On demande à l'utilisateur de choisir un fichier audio comme bande son
	SelectedFile=`zenity --file-selection --title "Veuillez choisir la bande sonore pour $1" --file-filter="Fichiers audio | *.ogg *.mp3 *.flac *.wma *.wav *.snd *.ra *.m4a *.mid"`
	if [ "$?" == 1 ] ; then exit 0
	fi
	
	# Si aucun fichier n'est seléctionné, renvoyer une erreur et quitter
	if [ "$SelectedFile" = "" ]; then
	if [ $# != 1 ]; then
  	zenity --error --text="Vous devez choisir un fichier pour la bande sonore !"
  	exit 0
	fi
fi
	# Si le fichier seléctionné est vide, renvoyer une erreur et quitter
	if [ `stat --printf="%s" "$SelectedFile"` = "0" ]; then
 	zenity --warning --text="Le fichier <b>$SelectedFile</b> est vide !"
 	exit 0
fi

	# On démarre les opérations d'encodage
	enc=`avconv -i "$1" -i "$SelectedFile" -acodec copy -vcodec copy "bande-sonore_$1" | zenity --progress --pulsate --title "Ajout de bande sonore" --text "Le fichier audio <b>$SelectedFile</b> en cours d'incorporation dans <b>$1</b>." --auto-close`
	notify-send -i /usr/share/icons/Humanity/apps/48/audio-player.svg "Ajout d'une bande sonore" "La bande sonore $SelectedFile a été correctement ajoutée à la vidéo $1 !";
fi
fi

	if [ "$option" = "Extraire la bande sonore" ]; then
	extrait=`avconv -i "$1" -vn -ac 2 -ar 44100 -ab 192k -f mp3 "$1".mp3 \
	| zenity --progress --width="500" --pulsate --title "Extraction de la bande sonore" \
	--text "Extraction audio de <b>$1</b> vers le format <b>mp3</b> en cours..." --auto-close`;
	notify-send -i /usr/share/icons/Humanity/apps/48/audio-player.svg "Extraction en MP3" "Le son de la vidéo $1 a été correctement extrait !";
fi

	if [ "$option" = "Supprimer la bande sonore" ]; then
	encodage=`avconv -i "$1" -an -vcodec copy "muet_$1" | zenity --progress --pulsate --title "Suppression de la bande sonore" --text "Suppression de la bande sonore de <b>$1</b> en cours..." --auto-close`;

	# Afficher résultat de la conversion
	if [[ $encode_video != 0 ]]; then
	notify-send -i /usr/share/icons/Humanity/apps/48/audio-player.svg "Suppression de la bande sonore" "Suppression de la bande sonore de $1 terminée !";
	else
	zenity --error --title "Erreur!" -- text "Echec du réencodage !";
fi
fi
