#!/bin/bash
########################################################################
#Script permettant de renommer toutes les vidéos d'un dossier
#Nom du script: Renommer les vidéos en masse v1.0
#Auteur: Astohan
#Site Web: http://ankala.fr
#Licence: GPL v3
#À venir en v1.1:
########################################################################
version="v1.0"

IFS="
"

let "indice=1"

	# Menu Principal
option=$(zenity --list --radiolist --width="480" --height="180" --title="Renommer les vidéos en masse $version" --text="Choisir un mode de renommage des vidéos." --column="Cocher" --column="Mode" --column="Description" \
TRUE "Numérique" "Renomme les vidéos en 1.avi, 2.avi etc..." \
FALSE "Préfixe" "Ajoute un préfixe avant chaque vidéo")

	# Option Numérique
	if [ "$option" = "Numérique" ]; then
	for fichier in *.avi *.AVI *.ogv *.OGV *.webm *.WEBM *.mp4 *.MP4 *.mkv *.MKV;
do
            if [ -f "$fichier" ]; then
            extension=${fichier##*.}
            echo "$fichier" "=>" "$nom-$indice.$extension"
            mv "$fichier" `printf "%02d" $indice`".$extension"
            let "indice+=1"
        fi
done
fi

	# Option Préfixe
	if [ "$option" = "Préfixe" ]; then
	nom=$(zenity --entry --title="Renommer les vidéos en masse $version" --entry-text="video" --text="Entrez le préfixe commun à chaque vidéo. \nLa numérotation s'y ajoutera automatiquement.\n\nPar exemple: vidéo pour vidéo-1.png, vidéo-2.png et ainsi de suite.")
	if [ "$?" == 1 ] ; then return 1
	else
	for fichier in *.avi *.AVI *.ogv *.OGV *.webm *.WEBM *.mp4 *.MP4 *.mkv *.MKV;
do
            if [ -f "$fichier" ]; then
            extension=${fichier##*.}
            echo "$fichier" "=>" "$nom-$indice.$extension"
            mv "$fichier" "$nom-"`printf "%02d" $indice`".$extension"
            let "indice+=1"
        fi
done
fi
fi
