#!/bin/bash
########################################################################
#Script permettant d'extraire les calques d'une image PSD
#Nom du script: Extraire les calques du PSD v1.0
#Auteur: Astohan
#Site Web: http://ankala.co.cc
#Source:Documentation de ImageMagick
#Licence: GPL v3
########################################################################
version="v1.0"
IFS="
"
	# On s'assure qu'un fichier est seléctionné
	mime=`file -bi "$1"`;
	correct_image="0";
	
	# On s'assure que ce fichier est dans le bon format
	if echo "$1" | grep -q '.psd'|| echo "$1" | grep -q '.PSD'; then
		audio_type="psd"
		correct_format="1"

	# On affiche une erreur si aucun fichier n'est seléctionné
	elif [ $1 -eq 0 ]; then
		zenity --error --title="Erreur" --text="Vous devez sélectionner au moins une image..."
		exit 1
	
	# On affiche une erreur si ce fichier est dans un format non-supporté
	elif [ $correct_video -eq 0 ]; then
		zenity --error --title="Erreur - Format non supporté -" --text="Sélectionnez une ou plusieurs image au format psd valide."
		exit 1
	
	# On affiche une erreur si le script ne reconnait pas le fichier
	else
		zenity --error --title="Erreur" --text="Erreur inconnue. Réessayez !"
		exit 1
	fi

	# Si le format du fichier est correct, on démarre l'opération
	if [ $correct_format -eq "1" ]; then
convert $@ $1.png \
| zenity --progress --width="500" --pulsate --title "Extraction des images calques en cours..." \
--text "Les images calques présentes dans l'image PSD $1 sont en train d'être extraites." --auto-close
fi

