#!/bin/sh
########################################################################
#Script permettant de compresser la taille des images Jpg
#Nom du script: Compresser les JPG v1.1
#Auteur: Astohan
#Site Web: http://ankala.co.cc
#Source:Documentation de ImageMagick
#Licence: GPL v3
#À venir en v1.2: ?
########################################################################
version="v1.1"

	# On s'assure qu'un fichier est seléctionné
	mime=`file -bi "$1"`;
	correct_image="0";
	
	# On s'assure que le fichier est dans le bon format: jpg
	if echo "$1" | grep -q '.jpg'|| echo "$1" | grep -q '.JPG'; then
		echo "File is in .jpg Format"
		image_type="jpg"
		correct_image="1"
	elif echo "$1" | grep -q '.jpeg'|| echo "$1" | grep -q '.JPEG'; then
		echo "File is in .jpeg Format"
		image_type="jpeg"
		correct_image="1"
	elif [ $1 -eq 0 ]; then
		zenity --error --title="Erreur" --text="Vous devez sélectionner une image..."
		exit 1
	elif [ $correct_image -eq 0 ]; then
		zenity --error --title="Erreur - Format non supporté -" --text="Sélectionnez au moins une image au format <b>jpg</b> valide."
		exit 1
	else
		zenity --error --title="Erreur" --text="Erreur inconnue. Réessayez !"
		exit 1
	fi

	# Si le fichier est dans le bon format, on permet les options de compression
	if [ $correct_image -eq "1" ]; then

	# On définit la qualité de l'image compressée
	compress=$(zenity --scale --title="Choix de la Qualité de l'image" --text "Définir la qualité de la compression (en %).\n\nPlus la qualité est élevée, plus le poids de l'image sera important." --value="85" --min-value="1" --max-value="100" --step="1")

	# On convertit l'image selon la variable $compress définie par l'utilisateur
	conversion=`mogrify -quality $compress "$@" $compress%_$1.jpg\
		| zenity --progress --width="500" --pulsate --title "Compression des images en cours..." \
		--text "Compression des images avec Qualité $compress %." --auto-close`;
	
	# On affiche une notification de réussite
	notify-send "Compression des JPG" "Compression des images JPG (taux de $compress %) terminée avec succès !";
	fi
fi
done



