#!/bin/sh
########################################################################
#Script permettant de compresser la taille des images Jpg
#Nom du script: Compresser les JPG v1.1
#Auteur: Astohan
#Site Web: http://ankala.fr
#Source: Documentation de ImageMagick
#Licence: GPL v3
#À venir en v1.2: ?
########################################################################
version="v1.1"

	# On s'assure qu'un fichier est sélectionné et du MIME "image"
	mime=`file -bi "$1"`;
	correct_image=`echo "$mime" | grep image | wc -l`;

	# Si le fichier n'est pas de MIME "image"...
	if [ ! $correct_image -eq 1 ]; then
		zenity --error --title="Compresser les JPG $version" --text="Veuillez sélectionner un fichier image valide."
		exit 1
	fi

	# Si le fichier est dans le bon format, on permet les options de compression
	if [ $correct_image -eq "1" ]; then

	# On définit la qualité de l'image compressée
	compress=$(zenity --scale --title="Choix de la Qualité de l'image" --text "Définir la qualité de la compression (en %).\n\nPlus la qualité est élevée, plus le poids de l'image sera important." --value="85" --min-value="1" --max-value="100" --step="1")

	# On convertit l'image selon la variable $compress définie par l'utilisateur
	conversion=`mogrify -quality $compress "$@" $compress%_$1.jpg\
		| zenity --progress --width="500" --pulsate --title "Compression des images en cours..." \
		--text "Compression des images avec Qualité $compress %." --auto-close`;
	
	# On affiche une notification de réussite
	notify-send -i /usr/share/icons/Humanity/categories/48/applications-viewers.svg "Compression des JPG - $compress %" "Compression des images JPG terminée !";
	fi
fi
done



