#!/bin/bash
########################################################################
#Script convertissant les images d'un format vers un autre
#Nom du script: Convertir l'image en v1.0
#Auteur: Astohan
#Site Web: http://ankala.fr
#Source: Documentation de imagemagick
#Licence: GPL v3
#À venir en v1.2: Donner plus de formats en sortie
########################################################################
version="v1.1"

IFS="
"
########################### PRÉ-REQUIS #################################

	# On s'assure qu'un fichier est sélectionné et du MIME "image"
	mime=`file -bi "$1"`;
	correct_image=`echo "$mime" | grep image | wc -l`;

	# Si le fichier n'est pas de MIME "image"...
	if [ ! $correct_image -eq 1 ]; then
		zenity --error --title="Convertir les images $version" --text="Veuillez sélectionner un fichier image valide."
		exit 1
	fi

	# Menu sélection du format de sortie 
	option=`zenity --list --width="300" --height="200" --title="Convertir les images $version" --text="Choisir un format dans lequel les images seront converties." --column="Format" --column="Description" \
	"PNG" "Convertir en PNG" \
	"JPEG" "Convertir en JPEG" \
	"GIF" "Convertir en GIF" `;


	if [ "$option" = "PNG" ]; then
	file=$1
	basename=${file%.*}
	convert_image=`convert "$@" "$basename".png \
	| zenity --progress --width="500" --pulsate --auto-close --title "Conversion des images $version" \
	--text "Conversion des images vers le format <b>PNG</b> en cours..."`;

	# Image d'origine est SVG
	if echo "$1" | grep -q '.svg$'; then
	encode_image=`convert -background none "$@" "$basename".png \
	| zenity --progress --width="500" --pulsate --auto-close --title "Conversion des images $version" \
	--text "Conversion des images SVG vers le format <b>PNG</b> en cours..."`;
	fi
	
	fi

#####################################
	# Conversion vers format 'jpg'
	if [ "$option" = "JPEG" ]; then
	file=$1
	basename=${file%.*}
	convert_image=`convert "$@" "$basename".jpg \
	| zenity --progress --width="500" --pulsate --auto-close --title "Conversion des images $version" \
	--text "Conversion des images vers le format <b>JPEG</b> en cours..."`;
	fi

####################################
	# Conversion vers format 'gif'
	if [ "$option" = "GIF" ]; then
	file=$1
	basename=${file%.*}
	convert_image=`convert "$@" "$basename".gif \
	| zenity --progress --width="500" --pulsate --auto-close --title "Conversion des images $version" \
	--text "Conversion des images vers le format <b>GIF</b> en cours..."`;
	fi

	# Afficher résultat de la conversion
	if [[ $convert_image != 0 ]]; then
	notify-send -i /usr/share/icons/Humanity/categories/48/applications-viewers.svg "Conversion des images - $option" "La conversion des images est terminée !";
	else
	zenity --error --title "Erreur!" -- text "Echec de la conversion !";
	fi
