#!/bin/bash
########################################################################
#Script permettant de renommer les fichiers JPG ou jpeg en jpg
#Nom du script: Renommer JPG & jpeg en jpg v1.0
#Auteur: Astohan
#Site Web: http://ankala.co.cc
#Licence: GPL v3
#À venir en v1.1: ?
########################################################################
version="v1.0"
IFS="
"

####################################

	# On renomme tous les fichiers JPG et jpeg présents dans le dossier courant
rename 's/\.jpe?g$/.jpg/i' *
notify-send "Renommer les JPG & jpeg" "Tous les fichiers JPG & jpeg du répertoire courant ont été renommés en jpg avec succès !"
