#!/bin/bash
########################################################################
#Script générant une galerie simple ou personalisée des images
#Nom du script: Galerie d'images v1.0
#Auteur: Astohan
#Site Web: http://ankala.fr
#Source: Documentation de ImageMagick
#Licence: GPL v3
########################################################################
version="v1.0"
IFS="
"
	# On s'assure qu'un fichier est sélectionné et du MIME "image"
	mime=`file -bi "$1"`;
	correct_format=`echo "$mime" | grep image | wc -l`;

	# Si le fichier n'est pas de MIME "image"...
	if [ ! $correct_format -eq 1 ]; then
		zenity --error --title="Galerie d'images $version" --text="Veuillez sélectionner un fichier image valide."
		exit 1
	fi

	# Si le format du fichier est correct, on démarre l'opération
	if [ $correct_format -eq "1" ]; then

	# Menu principal
	option=`zenity --list --width="550" --height="200" --title="Générer la galerie des images $version" --column="Option" --column="Description" \
	"Galerie légère" "Galerie de miniatures légère" \
	"Galerie simple" "Galerie sobre et sans effets" \
	"Galerie polaroide" "Galerie personnalisée avec effet polaroide" `;
	
	if [ "$option" = "Galerie légère" ]; then
	# On crée le répertoire 'galerie'
	mkdir galerie_mini
		# On démarre l'opération Galerie
	convert_galeriemini=`montage -label \"%f\" $@ -frame 5 -geometry 100x100 galerie_mini/galerie.png \
	| zenity --progress --width="500" --pulsate --title "Ajout de l'effet Galerie de photos en cours..." \
	--text "Application de l'effet <b>Galerie de photos</b> sur les images sélectionnées." --auto-close`;
	fi
	
	if [ "$option" = "Galerie simple" ]; then
	# On crée le répertoire 'galerie'
	mkdir galerie_simple
		# On démarre l'opération Galerie
	convert_galeriesimple=`montage $@ galerie_simple/galerie.png \
	| zenity --progress --width="500" --pulsate --title "Ajout de l'effet Galerie de photos en cours..." \
	--text "Application de l'effet <b>Galerie de photos</b> sur les images sélectionnées" --auto-close`;
	fi	
	
	if [ "$option" = "Galerie polaroide" ]; then
	# On crée le répertoire 'galerie'
	mkdir galerie_polaroide
		# On démarre l'opération Galerie
	caption=`zenity --entry --title="Titre de la galerie polaroide" --text="Veuillez entrer le titre de la galerie polaroide."`
	convert_montage=`montage $@ -thumbnail 300x300 -set caption %t -bordercolor "#E6E6FA" -background grey40 -pointsize 9 -density 144x144 +polaroid -resize 50%  -background white -geometry +1+1 -title "$caption" galerie_polaroide/galerie.png \
	| zenity --progress --width="500" --pulsate --title "Ajout de l'effet Galerie de photos en cours..." \
	--text "Application de l'effet <b>Galerie de photos</b> sur les images sélectionnées." --auto-close`;
	fi
fi
