#!/bin/bash
########################################################################
#Script permettant de réduire le poids d'un fichier PDF
#Nom du script: Compresser un PDF v1.0
#Auteur: Astohan
#Site Web: http://ankala.fr
#Licence: GPL v3
#À venir en v1.1:
########################################################################
version="v1.0"
IFS="
"
	# On s'assure qu'un fichier est seléctionné
	mime=`file -bi "$1"`;
	correct_format="0";
	taille=`ls -lah $1 | awk '{ print $5}'`;


	# On s'assure que ce fichier est dans le bon format; pdf
	if echo "$1" | grep -q '.pdf'|| echo "$1" | grep -q '.PDF'; then
		echo "File is in .pdf Format"
		format_type="pdf"
		correct_format="1"
	elif [ $1 -eq 0 ]; then
		zenity --error --title="Erreur" --text="Vous devez sélectionner un fichier PDF..."
		exit 1
	elif [ $correct_format -eq 0 ]; then
		zenity --error --title="Erreur - Format non supporté -" --text="Sélectionnez un fichier <b>pdf</b> valide."
		exit 1
	else
		zenity --error --title="Erreur" --text="Erreur inconnue. Réessayez !"
		exit 1
	fi

	# Si le format du fichier est correct, on affiche la compression
	if [ $correct_format -eq "1" ]; then
	# On informe l'utilisateur de la suite des opérations
	question=$(zenity --question --title="Compresser un PDF $version" --text "Vous êtes sur le point de compresser le fichier PDF <b>$1</b> sélectionné.\n\n \
Cela aura pour conséquence de réduire sa taille sur le disque, au risque possible d'une légère perte de qualité de l'image.\n\n \
Voulez-vous procéder à la compression de ce fichier PDF ?")

	# S'il valide la fenêtre, on démarre l'opération de compression du PDF
	if [ "$?" == 0 ] ; then 

gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile="compressé_$1" $1 | zenity --progress --title "Compression en cours..." --text "Le fichier <b>$1</b> est en train d'être compressé." --pulsate --auto-close | notify-send "Compression du PDF" "La compression du fichier $1 est terminée !"

	# S'il refuse, on quitte le script
	else
	exit 1

fi
fi
