#!/bin/bash
########################################################################
#Script permettant de protéger un fichier PDF en écriture (copier/coller impossible)
#Nom du script: Protéger un PDF v1.0
#Auteur: Astohan
#Site Web: http://ankala.co.cc
#Licence: GPL v3
#À venir en v1.1:
########################################################################
version="v1.0"
IFS="
"

	# On s'assure que 'pstotext' est bien installé
	pstotext_exists=`which pstotext | grep -c "pstotext"`

	# On affiche une erreur si 'pstotext' n'est pas installé
	# On tente une installation automatique de 'pstotext'
	if [ $pstotext_exists -eq 0 ]; then
	pstotext_error=`zenity --error --title="Erreur - Outil de conversion manquant !" --text="Vous devez installer le paquet pstotext afin d'utiliser ce script.\n\nTentative d'installation automatique amorcée."`;
	install_pstotext=`gksudo apt-get install pstotext | zenity --progress --pulsate --title "Installation de pstotext" --text "Installation en cours..." --auto-close`;
	fi

	# On s'assure que l'installation automatique de 'pstotext' a réussi
	pstotext_exists2=`which pstotext | grep -c "pstotext"`
	
	# Si ce n'est pas le cas, on affiche une erreur et on quitte
	if [ $pstotext_exists2 -eq 0 ]; then
		zenity --error --title="Erreur détectée !" --text="ERREUR: La tentative d'installation automatique a échouée. Veuillez installer pstotext manuellement, à partir de votre terminal: sudo apt-get install pstotext";
		exit;
	fi

	# On s'assure qu'un fichier est seléctionné
	mime=`file -bi "$1"`;
	correct_format="0";

	# On s'assure que ce fichier est dans le bon format; pdf
	if echo "$1" | grep -q '.pdf'|| echo "$1" | grep -q '.PDF'; then
		echo "File is in .pdf Format"
		format_type="pdf"
		correct_format="1"
	elif [ $1 -eq 0 ]; then
		zenity --error --title="Erreur" --text="Vous devez sélectionner un fichier PDF..."
		exit 1
	elif [ $correct_format -eq 0 ]; then
		zenity --error --title="Erreur - Format non supporté -" --text="Sélectionnez un fichier <b>pdf</b> valide."
		exit 1
	else
		zenity --error --title="Erreur" --text="Erreur inconnue. Réessayez !"
		exit 1
	fi

	# Si le format du fichier est correct, on affiche la compression
	if [ $correct_format -eq "1" ]; then
	file="$1"
	pstotext $1 > ${file%.*}.txt | zenity --progress --title "Compression en cours..." --text "Le fichier <b>$1</b> est en train d'être converti en un fichier TXT <b>${file%.*}.txt</b>." --pulsate --auto-close;
notify-send "Conversion du PDF en TXT" "La conversion de $1 en ${file%.*}.txt est terminée !"

fi

