#!/bin/bash
########################################################################
#Script permettant d'xtraire les images individuelles dun gif animé
#Nom du script: Extraire les images du gif v1.0
#Auteur: Astohan
#Site Web: http://ankala.fr
#Source: Documentation de ImageMagick
#Licence: GPL v3
########################################################################
version="v1.0"


	# On s'assure qu'un fichier est sélectionné et du MIME "image"
	mime=`file -bi "$1"`;
	correct_image=`echo "$mime" | grep image | wc -l`;

	# Si le fichier n'est pas de MIME "image"...
	if [ ! $correct_image -eq 1 ]; then
		zenity --error --title="Extraire les images du Gif $version" --text="Veuillez sélectionner un fichier image valide."
		exit 1
	fi

	# Si le fichier est dans le bon format
	if [ $correct_image -eq "1" ]; then
montage $1 -tile x1 -geometry '1x1+0+0<' -alpha On -background "rgba(0, 0, 0, 0.0)" -quality 100 sheet_$1.png \
| zenity --progress --width="500" --pulsate --title "Extraction des images en cours..." \
--text "Extraction des images de $1." --auto-close
fi

