#!/bin/bash
########################################################################
#Script permettant de remplacer les espaces (dans les noms de fichiers) par des sous-tirets
#Nom du script: Remplacer Espaces par Sous-tirets v1.1
#Auteur: Astohan
#Site Web: http://ankala.co.cc
#Licence: GPL v3
#À venir en v1.2: ?
########################################################################
version="v1.1"	# Améliorations diverses & ajout de fonctionalités
IFS="
"
	# On affiche le menu principal sous forme de liste-radio
	option=`zenity --list --radiolist --width="680" --height="215" --title="Remplacer les Espaces $version" --text="Il peut être utile de remplacer les espaces vides (simples uniquement) par des sous-tirets (underscore)\ndans les noms de fichiers et dossiers, notamment lorsque l'on navigue dans un terminal unix." --column="Cocher" --column="Action" --column="Description" \
	TRUE "Dossiers & Fichiers" "Corrige les noms des dossiers & fichiers du premier niveau" \
	FALSE "Tout le contenu" "Corrige les noms de tous les dossiers & fichiers à tous les niveaux" `;
	if [ "$?" == 1 ] ; then exit 0 
	else
	if [ "$option" = "Dossiers & Fichiers" ]; then
	# On remplace les espaces des fichiers et dossiers du répertoire courant par des tirets
for file in *;do rename 'y/ /_/' *;done
	# On affiche une notification de réussite
	notify-send "Remplacement des Espaces" "Les espaces vides des noms de fichiers et dossiers (du dossier courant) ont été remplacés par des sous-tirets avec succès !"
fi
	if [ "$option" = "Tout le contenu" ]; then
find -name "* *" -type d | rename 's/ /_/g'	# dossiers
find -name "* *" -type f | rename 's/ /_/g'	# fichiers
	notify-send "Remplacement des Espaces" "Les espaces vides des noms de fichiers et dossiers (de tous les dossiers du répertoire courant) ont été remplacés par des sous-tirets avec succès !"
fi
fi
