#!/bin/bash
########################################################################
#Script permettant de remplacer les MAJUSCULES (dans les noms de fichiers) par des minuscules
#Nom du script: Remplacer MAJUSCULES par minuscules v1.0
#Auteur: Astohan
#Site Web: http://ankala.co.cc
#Licence: GPL v3
#À venir en v1.2: ?
########################################################################
version="v1.1"	# Polissage du script
IFS="
"
	# On affiche le menu principal sous forme de liste-radio
	question=$(zenity --question  --title="Remplacer les MAJUSCULES $version" --text="Ce script va remplacer toutes les lettres en <b>MAJUSCULE</b> par des lettres en <b>minuscule</b> dans les noms\nde fichiers et dossier du répertoire courant.\n\nVoulez-vous procéder à l'opération ?")
	if [ "$?" == 1 ] ; then exit 0 
	else

	# On remplace les majuscules des fichiers et dossiers du répertoire courant par des minuscules
for file in *;do rename 'y/A-Z/a-z/' *;done
	# On affiche une notification de réussite
	notify-send "Remplacement des MAJUSCULES" "Les lettres en MAJUSCULE des noms de fichiers et dossiers (du dossier courant) ont été remplacés par des lettres en minuscule avec succès !"
fi
