#!/bin/bash
########################################################################
#Script permettant d'installer une clé de registre dans Wine (regedit)
#Nom du script: Installer une clé de registre v1.0
#Auteur: Astohan
#Site Web: http://ankala.co.cc
#Licence: GPL v3
#À venir en v1.1:
########################################################################
version="v1.0"
IFS="
"
	# Selection de la clé de registre à installer dans Wine
	SelectedFile=`zenity --file-selection --title "Veuillez choisir la clé de registre à installer avec Wine" --file-filter="Clés de registre | *.reg *.txt"`

	# Si l'utilisateur annule, on quitte le script
	if [ "$?" == 1 ] ; then exit 1
	else
	# Erreur si le fichier est vide ou inexistant
	if [ `stat --printf="%s" "$SelectedFile"` = "0" ]; then
 zenity --warning --text="Le fichier <b>$SelectedFile</b> est vide !
Il est inutile de continuer !"
exit 0
fi
wine regedit "$SelectedFile"
	notify-send "Clé de registre" "La clé de registre $SelectedFile a été correctement intégrée dans Wine (regedit) !";
	fi
